#:kivy 1.11.0
#:import SlideTransition kivy.uix.screenmanager.SlideTransition

<Manager>:
    transition: SlideTransition()
    Progress:
        name: 'Progress'
    Patient:
        name: 'Patient'

    

<Patient>:
    BoxLayout:
        orientation: 'vertical'

        Label:
            text: 'Patient Screen'
            font_size: '30sp'

        Button:
            size_hint: 1, 0.1
            text: 'Goto Progress Screen'
            on_release:
                root.manager.current = 'Progress'

<Progress>:
    bar: bar

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
        

    BoxLayout:
        id: bar
        gra:

    Button:
        text:'Patient Menu'
        font_size: 20
        bold: True
        size_hint: None, None
        size: 300, 50
        pos_hint: {'center_x': .5, 'center_y': .1 }
        color: 1, 1, 1, 1
        on_press: root.manager.current = 'Patient'